## Testing weather coefficient creation function
start <-  2014
end <- 2017
timestep <- "weekly"
directory <- "G:/DaymetUS"
output_directory <- "G:/DaymetUS/test"
#output_directory <- dir.create("G:/DaymetUS/test")
states_of_interest <- c('Maryland')
pest <- "ECFF"
prcp_index = 'YES'
prcp_method = "threshold" 
prcp_a0 = 0
prcp_a1 = 0 
prcp_a2 = 0 
prcp_a3 = 0 
prcp_thresh = 2.5
temp_index = 'YES' 
temp_method = "polynomial" 
temp_a0 = -0.066
temp_a1 = 0.056
temp_a2 = -0.0036
temp_a3 = -0.0003
temp_x1mod = 0
temp_x2mod = -15
temp_x3mod = -15
temp_thresh = 0
